name: blog.neet.works deployment
#on:
#  push:
#    paths:
#      - 'public/**'  # Trigger the workflow when files in the 'public' folder are updated

on: [push]

jobs:
  deploy_mamizou:
    runs-on: mamizou
    run-name: Deploy blog.neet.works on Mamizou
    steps:
      #evil
      - run: ssh $USER@localhost -p 2244
      - run: pwd
      - run: cd /srv/http/blog.neet.works
      - run: git pull
      - run: git checkout
