name: blog.neet.works deployment
#on:
#  push:
#    paths:
#      - 'public/**'  # Trigger the workflow when files in the 'public' folder are updated

on: [push]

jobs:
  deploy_mamizou:
    runs-on: mamizou
    run-name: Deploy blog.neet.works on Mamizou
    steps:
      - run: git pull
      - run: git checkout
