name: blog.neet.works deployment
on:
  push:
    paths:
      - 'public/**'  # Trigger the workflow when files in the 'public' folder are updated

jobs:
  deploy_mamizou:
    runs-on: mamizou_neet_works_static_deploy
    run-name: Deploy blog.neet.works on Mamizou
    steps:
      - run: cd /srv/http/blog.neet.works/
      - run: git pull
      - run: git checkout
